### ISSUE TITLE
segfault in regexp

### ISSUE THREAD

**Issue by samth** [pycket/pycket#262]
```
[samth@huor:~/.../racket-test-core/tests/racket (master) plt] pk 
Welcome to Pycket v7.1.0.6
> (regexp-replace* "" "123" "b")
Aborted (core dumped)
```

**Comment by samth** [comment]
This works correctly with the jit off. :(

**Comment by krono** [comment]
we're using rpython's `rsre`, and I vaguely remember that PyPy has its own JIT for regexen. If we do, too, through `rsre`, maybe we could discern which jit crashes. If we don't, maybe having one is a way out.

**Comment by samth** [comment]
We do jit regexps, so the issue is probably there.

**Comment by cderici** [comment]
This is not a bug in Pycket's `regexp-replace*` primitive, it happens because we're doing something wrong that causes the `-regexp-replace*` in `string.rkt` to fail.

$ p -c -I racket/private/pre-base
Welcome to Pycket v7.1.0.6
\> (regexp-replace* "" "123" "b")
b1b2b3b
\> (require racket/private/base) 
\> (regexp-replace* "" "123" "b")
RACKET -- string.rkt : -regexp-replace* <-- this is a `printf` I put in `string.rkt`
Aborted

**Comment by cderici** [comment]
Here's a call that causes the issue in the above interaction:

`(regexp-match-positions/end #rx"(?:)(?<=.)" "123" 0 #f #f #"" 1000)`

(This call is made at `racket/private/string.rkt` )

I tracked it down to the `getwidth` method of classes derived from `RegexpBase` in `pycket/regexp.py`. This is only a matter of implementing `getwidth` on each of those classes. Currently only the two of them (`Character` and `Property`) has it.

Implementing a placeholder for `getwidth` methods on those classes will avoid a segfault, but obviously will return incorrect results. The correct implementation for that in each class is not clear to me at the moment.

**Comment by samth** [comment]
This causes `raco setup racket` to fail.
